### ISSUE TITLE
Duplicated F0-4 packets

### ISSUE THREAD

**Issue by lucari** [mrrwa/core#1]
Despite the values set for F0-4, a packet with all fields set to zero is received.

The problem seems to be related to NrmaDcc.cpp and a hidden 'break' statement at line 484. This should be swapped with the #endif on the next line. The result is that when a Speed packet is processed, it drops through to the next case statement and sends an empty DCCFunc command.

**Comment by kiwi64ajs** [comment]
Ah yes, you're right. I've made the suggested change
